### ISSUE TITLE
Show angel hours already worked

### ISSUE THREAD

**Issue by plumpudding** [ccchh/angel-news-hub#14]
For example next to the hours to be worked
Are the really early buildup hours like the *OC's in the engelsystem?

**Comment by zeidlos** [comment]
We don't need that. For brevity it should be either hours to be worked or hours already worked.
For the sake of teambuilding, we preferred a countdown.

No, the buildup/teardown shifts are not in the angel system. And not all *OCs are in the angel system either.

**Comment by plumpudding** [comment]
I think it'd be nice, but if you think different we'll leave it like it is.
